server:
  servlet:
    context-path: /api/product
spring:
  application:
    name: product

  datasource:
    url: jdbc:mysql://localhost:3306/db_product?createDatabaseIfNotExist=true
    username: root
    password: zahiri
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration